### ISSUE TITLE
Failing devel job breaks other prereleases

### ISSUE THREAD

**Issue by dirk-thomas** [moveit/moveit_core#181]
Your devel job (http://jenkins.ros.org/job/devel-indigo-moveit_core/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/2/console) is failing due to wrong / incomplete CMake.

This also effects other package since it breaks prereleases as well, e.g.: http://jenkins.ros.org/job/prerelease-indigo-orocos_kinematics_dynamics/2/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=prerelease/console

Please fix the problems and rerelease the packages.

**Comment by davetcoleman** [comment]
Looks like the package `angles` needs to be added to `find_package(catkin REQUIRED COMPONENTS)`? Currently its only `find_package(angles)` [here](https://github.com/ros-planning/moveit_core/blob/hydro-devel/CMakeLists.txt#L31)

Problem:

> /tmp/test_repositories/src_repository/moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h:45:27: fatal error: angles/angles.h: No such file or directory
>  #include <angles/angles.h>

**Comment by k-okada** [comment]
I'm not sure, but you need to add agnles to `build_depend` if other build_depend package did not depends on angles
https://github.com/ros-planning/moveit_core/blob/hydro-devel/package.xml

;; from the next room...

**Comment by davetcoleman** [comment]
I think this was fixed, above

**Comment by dirk-thomas** [comment]
The referenced patch in #190 looks pretty wrong to me.

**Comment by davetcoleman** [comment]
New fix attempted.

**Comment by dirk-thomas** [comment]
This is still not fixed. The problem describes indigo but the correct patch was applied to hydro only (I did not even check if it was broken on hydro). But indigo still only contains the incomplete PR.

**Comment by mikeferguson** [comment]
@dirk-thomas the devel job is now running but unstable, is that enough for this ticket?

(there are individual tickets already covering the tests that are (still) failing)

**Comment by dirk-thomas** [comment]
Yes, this was all about the compile-from-source failing other downstream packages. The maintainers can handle the test failures however they want. Thanks.
